services:
  db:
    image: ghcr.io/reinanhs/jud-db:latest
    container_name: postgres_jud_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: jud_db
      TZ: America/Sao_Paulo
    command: postgres -c timezone=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:26.0.3
    container_name: cloudbeaver_jud
    environment:
      CB_SERVER_NAME: "JUD Database"
      CB_SERVER_URL: "http://localhost:8978"
      CB_ADMIN_NAME: "cbadmin"
      CB_ADMIN_PASSWORD: "Admin123"
      CLOUDBEAVER_APP_ANONYMOUS_ACCESS_ENABLED: "true"
      CLOUDBEAVER_APP_GRANT_CONNECTIONS_ACCESS_TO_ANONYMOUS_TEAM: "true"
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
      - ./.docker/cloudbeaver/initial-data.conf:/opt/cloudbeaver/conf/initial-data.conf
      - ./.docker/cloudbeaver/data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    restart: unless-stopped
    depends_on:
      - db

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana_jud
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_SERVER_HTTP_PORT: 3000
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/jud_dashboard.json
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      TZ: America/Sao_Paulo
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./.docker/grafana/provisioning:/etc/grafana/provisioning
      - ./.docker/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
  cloudbeaver_data:
  grafana_data:
